[build]
  publish = "build"
  command = "npm run build"

[context.production.environment]
  NODE_VERSION = "20.18.1"

[site]
  name = "rat-chat-app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
